### ISSUE TITLE
Determining Local Font Name?

### ISSUE THREAD

**Issue by areeves87** [ropensci/pdftools#29] opened 2018-03-18 17:40 UTC
As of now pdftools can extract **global** font information -- that is, all fonts used in a single document. I'd like to get **local** font information. Ideally, I'd like to determine the font used for each word in a page of text. Are there existing methods for this in the pdftools package? Or am I better off using a different package?

For instance, the sample pdf (http://arxiv.org/pdf/1403.2805.pdf) has several different fonts for the first page. I'd like to know which words use a given font. 

In my case, I want to tag bolded words extracted from my pdf of interest. I used PDF-Xchange viewer to manually determine that the bolded words are using a different, bolded version of the original font. Since there are thousands of bolded words, I'd like a procedure to automatically identify and tag them during the text extraction process.

I've attached the pdf of interest. See page 195 for an example.
[Flavor-Bible-epub.pdf](https://github.com/ropensci/pdftools/files/1822966/Flavor-Bible-epub.pdf)

**Comment by jeroen** [comment] 2018-03-19 02:56
There is currently some work going on by @mpsuzuki and @adamreichold to expose a wordlist api in the poppler C++ frontend that we use. But I am not sure if this includes font or markup information.

**Comment by mpsuzuki** [comment] 2018-03-19 03:14
Dear @jeroen and @areeves87,

Thank you for mention about my activity, I'm glad to find that I'm not the only one person trying to extract the word with font information. The current wordlist API of cpp frontend of poppler do not have font information, but I was trying to extend the API to include such infos. My work-in-progress code is here:
https://github.com/mpsuzuki/poppler/compare/add-textlist-to-cpp_with-font
(sorry, the last update was about 3 months ago, I should update for the latest poppler).

In my impression, the patch became too big and too broad (it requires the change in main part!), I'm afraid that the maintainer do not want to accept it. Anyway, I found there is another person who hope such feature, it would be not bad idea to ask "there is such request, can poppler help it?".

In my personal usecase, I inserted many debug printings into TextOutputDev part of the poppler and parse them by external scripts, to retrieve the position of the word, font, font size etc.

**Comment by areeves87** [comment] 2018-03-19 05:54
Thank you both for the info. 

You have my vote for including the feature in poppler,  @mpsuzuki . Unfortunately, I only have experience with R and I don't know c++ so I can't use your TextOutputDev method. But thank you for the suggestion.

**Comment by mpsuzuki** [comment] 2018-03-19 06:10
OK, for first, I would raise this feature request to poppler mailing list and hear the response. When the request is not considered well, we should discuss alternative methods.

BTW, pdftools of ropensci is expected to be "buildable with vanilla poppler (without kinky patches)"?

**Comment by mpsuzuki** [comment] 2018-03-19 14:05
Just I've updated
https://github.com/mpsuzuki/poppler/compare/add-textlist-to-cpp_with-font
branch to the latest master branch. All modifications are squashed.
"cpp/tests/poppler-dump --show-text-list Flavor-Bible-epub.pdf"
shows something like this.

Page 10/820:

[Food] @ ( x=5 y=8.2512 w=30.3304 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[and] @ ( x=38.1244 y=8.2512 w=22.4094 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[Drink] @ ( x=63.3278 y=8.2512 w=34.651 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[Combinations] @ ( x=101.493 y=8.2512 w=81.9325 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[WHAT] @ ( x=58.2871 y=26.9712 w=43.4506 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[TO] @ ( x=105.093 y=26.9712 w=20.5659 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[DRINK] @ ( x=129.577 y=26.9712 w=46.4894 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[WITH] @ ( x=178.543 y=26.9712 w=39.2884 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[WHAT] @ ( x=221.029 y=26.9712 w=43.4506 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[YOU] @ ( x=267.835 y=26.9712 w=31.281 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[EAT] @ ( x=302.4 y=26.9712 w=28.3286 h=12.8592 )( fontname=AAAAAB+LiberationSerif-Bold fontsize=14.4 wmode=0 )
[Classics] @ ( x=7.16029 y=46.1808 w=48.088 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[1996] @ ( x=58.2871 y=46.1808 w=28.8038 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[2000] @ ( x=195.825 y=46.1808 w=28.8038 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[2006] @ ( x=333.364 y=46.1808 w=28.8038 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[2008] @ ( x=365.048 y=46.1808 w=28.8038 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[We] @ ( x=5 y=77.8608 w=17.916 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[believe] @ ( x=26.6029 y=77.8608 w=42.3993 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[cooking] @ ( x=72.689 y=77.8608 w=45.366 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[will] @ ( x=120.935 y=77.8608 w=23.4463 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[continue] @ ( x=148.299 y=77.8608 w=47.4399 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[to] @ ( x=199.426 y=77.8608 w=10.8014 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[evolve,] @ ( x=213.828 y=77.8608 w=42.4857 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[and] @ ( x=259.914 y=77.8608 w=20.1627 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[not] @ ( x=283.677 y=77.8608 w=17.6856 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[only] @ ( x=304.56 y=77.8608 w=25.2034 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[as] @ ( x=332.644 y=77.8608 w=12.0832 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
[a] @ ( x=348.486 y=77.8608 w=6.39445 h=13.0896 )( fontname=AAAAAA+LiberationSerif fontsize=14.4 wmode=0 )
.....

**Comment by areeves87** [comment] 2018-03-19 19:19
Your output shows the correct local font name for each word. I am impressed!

I see that you have messaged the mailing list regarding your patch. I look forward to seeing the maintainers' response.

**Comment by areeves87** [comment] 2018-04-06 22:01
@mpsuzuki  I have seen a lot of activity in the poppler mailing list. Has the font info feature gotten any attention in the latest poppler commits?

**Comment by mpsuzuki** [comment] 2018-04-07 01:57
No, nobody commented about my patch.
There are a lot of activity in the poppler mailing list, but I'm impressed that most of them are the insertion of "const" to make the source less-vurnelable or less-useful-for-mistakenly-usage.
Maybe I should ask the status of my patch(es) to remind the queue.

**Comment by jeroen** [comment] 2018-04-07 12:25
I really appreciate your work @mpsuzuki! I can reply on the mailing list but the maintainer does not seem to care much about my opinion.

**Comment by mpsuzuki** [comment] 2018-04-12 03:08
Sorry, while I check the queues of my patches, I found that cpp-frontend encoding issue has some problems (saying more precisely, I should prepare more testcases which include Latin1 or PDFEncoding string in the metadata, and guarantee no regression). Please let me return to this issue after resolving that (maybe after April 20th).

**Comment by djkelleher** [comment] 2020-04-30 10:43
@mpsuzuki Were the issues with this ever resolved? I'm currently using the patch you linked above and everything seems to be working fine.

I'm curious to hear what happened to this. I find it surprising such a useful feature would be ignored by the maintainer.

**Comment by mpsuzuki** [comment] 2020-04-30 15:51
@djkelleher Oh, sorry for leaving this issue. I have been temporarily away from playing with poppler for a while, I should remember what had happened. A few public discussions are archived at:
[reconsideration about iconv() in cpp frontend](https://lists.freedesktop.org/archives/poppler/2018-April/013005.html)
[pdftotext font information](https://lists.freedesktop.org/archives/poppler/2018-May/013044.html)
Please let me spend a few days to remember where I stopped.

**Comment by jeroen** [comment] 2020-04-30 16:08
I think the poppler cpp encoding issue was solved eventually? At least for the wordlist api.

**Comment by mpsuzuki** [comment] 2020-05-01 08:54
Just I updated my font info patch to the head of the upstream.
https://github.com/mpsuzuki/poppler/tree/cpp-add-fontinfo-to-textlist
I don't know whether poppler maintainer could be interested in, but I would propose it again. 

NOTE: The mirror of github.com/freedesktop/poppler seems to be no longer updated, so please do not rely on github to compare my patch with the upstream. I would clone this branch to gitlab.freedesktop.org, and submit my merge request at there.

Oh, I'm not saying as "let's go to there to continue this discussion". I'm just saying about the mirrored poppler in github and future maintenance (if there is?) of my patch.

Regards,
mpsuzuki

**Comment by mpsuzuki** [comment] 2020-05-01 08:56
Ah, @jeroen, if you have some PDFs, please test the patched poppler-dump.

**Comment by jeroen** [comment] 2020-05-01 09:12
The poppler maintainer has become more responsive since they moved development to gitlab. You can send merge requests now, which is much better than mailing lists: https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests

**Comment by mpsuzuki** [comment] 2020-05-02 07:07
Just I've sent my first MR to poppler [[cpp]] Add the font infos to the text_box object.](https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/547). Hope something happens.

**Comment by mpsuzuki** [comment] 2020-05-20 01:41
My MR is just merged. The cpp API to retrieve the text_box with font infos would be available in the next official release. Thanks to everybody, and I apologize my laziness made you frustrated for a long time!

**Comment by Cdk29** [comment] 2020-09-03 08:49
I am really glad to read about this @mpsuzuki . I have used your experimental branch in January/March of this year for a project, and I was getting headaches about how the hell I could wrotte a makevar to make it works inside a R package. 

If I understand things properly, pdftools will now be able to got back the font directly ? Or should I need to fork pdftools and create a PR ? (I am not on a linux computer at the moment so I cannot really try this).

**Comment by Cdk29** [comment] 2020-09-20 11:20
I added some lines in poppler_pdf_data on [forked version here](https://github.com/Cdk29/pdftools/blob/master/src/bindings.cpp) to got the font and font size, but I will have to wait for Ubuntu 20 to have something more recent than the version 0.86 of poppler (the fonts info were inside the version 0.89).

**Comment by mpsuzuki** [comment] 2020-09-20 12:08
@cdk29 oh, sorry for my silence about your previous comment. I'm not a user of pdftools, just a contributor of poppler, so I guess the right way would be what you did. I apologize that I cannot finish the everything in my side. I hope the things left for the pdftools users are just waiting for the next release... thank you very much for putting the last piece!

**Comment by jeroen** [comment] 2020-09-20 13:26
@Cdk29 if you condition the new api calls inside a version macro, you can send a pr with your changes.

**Comment by Cdk29** [comment] 2020-09-20 16:04
@jeroen  I will try to do this. But I am actually unable to try the change locally, since Ubuntu does not have a recent enough version of poppler. Is it a problem ? The only thing I can tell is that Rcpp does not complain anylonger I install the forked version (except for the fact that the text_box does not have the font_size and size attribute).

@mpsuzuki Haha no sorry it is my fault, I understood that you were working on poppler and not pdftools, I should have made it more clear in my message.

**Comment by jeroen** [comment] 2020-09-20 17:55
You can test it on a `debian:testing` container

**Comment by Cdk29** [comment] 2020-10-01 17:13
I began to test locally on an Ubuntu 20.10 freshly installed. [The version here compile](https://github.com/Cdk29/pdftools/blob/master/src/bindings.cpp) (starting at line 193) but the output is quite disappointing : 

> edit common soon from second PC

Looking at the [poppler::text_box Class Reference
](https://poppler.freedesktop.org/api/cpp/classpoppler_1_1text__box.html) taking at exemple the existing : 

`space[j] = boxes.at(j).has_space_after();`

I wrote the following : 
`font_info[j] = boxes.at(j).has_font_info();`

Which output false all the time. I do not know C++ so much, So I wonder if there is not something obvious that I miss. Could someone gave me a hint or what could be wrong in my approach?

**Comment by mpsuzuki** [comment] 2020-10-02 01:29
@Cdk29 , thank you for trying to use that. It would be related with the optional switch to collect the font info during poppler::page::text_list().

https://poppler.freedesktop.org/api/cpp/classpoppler_1_1page.html#a9b467bd815233cd8fc0e672768af61a0

poppler::page::text_list() (as traditional style), it does not resolve the font information (this is because non-embedded font resolving needs some CPU power). To add the font information, we should call as poppler::page::text_list( poppler::page::text_list_include_font ).

I would take a look on pdftool in later (maybe next-next week). If you are in rush to see the working example, please check [cpp/tests/poppler_dump.cpp](https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/cpp/tests/poppler-dump.cpp)

Thank you very much for finding this misleading problem, I apologize that the class reference text is insufficient to help the users, I would make a merge request to improve this.

Also, I have to remind another point. The text_box::char_bbox() returns rectf(0,0,0,0) for too large glyph index, but no such mechanism is in text_box::get_font_name(). I have to propose some change for the people who have care on the font name but no care on the bounding box.

**Comment by Cdk29** [comment] 2020-10-02 07:24
@mpsuzuki Ahh yes indeed :D I managed to get it work ^^ I just need to polish a bit the code to put the opt_flag option inside a version macro based on the poppler version on the machine building the library and I would be able to PR.

You are welcome, but please do not take my difficulties with the class reference too seriously, I am far from a regular cpp programmer, and now that I am reading the _The option flag should be the multiple of text_list_option_enum._ , the reason seems obvious to me now that I have the working solution. I should have read with more attention the poppler::page Class Reference. I actually took a look at the poppler_dump.cpp yesterday without notifying it.

**Comment by Cdk29** [comment] 2020-10-02 09:03
PR sent !

**Comment by Cdk29** [comment] 2020-10-07 05:37
I hope it did not get loss in all the PRs spams of hacktoberfest :p

**Comment by jeroen** [comment] 2020-10-07 07:24
I'll try to look at this soon!

**Comment by Cdk29** [comment] 2021-01-30 14:54
@jeroen have you more time now ?

**Comment by jeroen** [comment] 2021-01-31 23:35
Merged via https://github.com/ropensci/pdftools/pull/86

**Closed by jeroen** 2021-01-31 23:35 UTC
